### ISSUE TITLE
PHP (or modifier 14) apps broken since 2.0.11.2

### ISSUE THREAD

**Issue by ultrabug** [unbit/uwsgi#1083]
After upgrading to **2.0.11.2**, our PHP applications break with a `unavailable modifier requested: 0` error.

This looks related to https://github.com/unbit/uwsgi/commit/a3caf3651503f1647fff299619af84cfc19b4485.

On nginx, we pass down the `uwsgi_modifier1 14;`, which is how our apps were working since then. Did something change or is it a real bug ?

Cheers

**Comment by unbit** [comment]
do you have a fastrouter with subscriptions setup ?

**Comment by ultrabug** [comment]
@unbit yes

**Comment by unbit** [comment]
in such a case the subscription has priority over nginx (this was the bug fixed in the specified commit as without it the backend has no way to set the modifier), so you should add modifier1=14 in the subscribe2 option, or load the php plugin as the zero one with plugins = 0:php.

**Comment by ultrabug** [comment]
Thanks @unbit gonna try asap and let you know / close this issue. Just to be sure tho, I need to remove the nginx modifier config and put it in the ini then right ?

**Comment by xrmx** [comment]
@ultrabug feel free to open a pull request to document this in uwsgi-docs ;)

**Comment by xrmx** [comment]
@ultrabug hi, can we close this?

**Comment by ultrabug** [comment]
Sure @xrmx , I'll do my best to get the chance to migrate our current setups and reopen if I still get stuck. Cheers.

About the PR, I'll try too or maybe @Lujeni could do it too <3

**Comment by xrmx** [comment]
@ultrabug thanks!
