### ISSUE TITLE
High memory usage/leak in HTTP(S) router with uWSGI 2.0.7->2.0.10

### ISSUE THREAD

**Issue by edevil** [unbit/uwsgi#963]
I've recently upgraded uWSGI from 2.0.7 to 2.0.10, and have noticed an increase in memory usage in the HTTP(S) router. Today I restarted 2 instances, one with 2.0.7 and another with 2.0.10, both receive the same kind of traffic, it is load-balanced between the two. Even though it has only been running for a few hours, already we can see a difference:

2.0.10
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
www-data 18452  1.3  0.8 1183828 138456 ?      Sl   11:32   2:14 discoapi uWSGI master
www-data 18457  1.6  0.5 1305808 95648 ?       Sl   11:32   2:54  \_ discoapi uWSGI worker 1
www-data 18458 17.5  1.1 1357408 186152 ?      Sl   11:32  30:18  \_ discoapi uWSGI worker 2
www-data 18459  4.3  0.7 1325168 117520 ?      Sl   11:32   7:26  \_ discoapi uWSGI worker 3
www-data 18460  7.8  1.0 1367988 172856 ?      Sl   11:32  13:33  \_ discoapi uWSGI worker 4
www-data 18461  5.7  0.9 1329960 154440 ?      Sl   11:32   9:55  \_ discoapi uWSGI worker 5
www-data 18462  1.3  0.4 1301668 78688 ?       Sl   11:32   2:17  \_ discoapi uWSGI worker 6
www-data 18463  2.7  0.6 1313048 98664 ?       Sl   11:32   4:46  \_ discoapi uWSGI worker 7
www-data 18464 20.4  1.1 1365676 187348 ?      Sl   11:32  35:15  \_ discoapi uWSGI worker 8
www-data 18465  4.2  0.9 1369668 163788 ?      Sl   11:32   7:22  \_ discoapi uWSGI worker 9
www-data 18466 10.5  1.0 1342500 174984 ?      Sl   11:32  18:09  \_ discoapi uWSGI worker 10
www-data 18467  1.3  0.9 1368048 157780 ?      Sl   11:32   2:17  \_ discoapi uWSGI worker 11
www-data 18468 13.3  1.1 1359296 190268 ?      Sl   11:32  23:03  \_ discoapi uWSGI worker 12
www-data 18469 30.6  1.3 1426104 214680 ?      Sl   11:32  52:47  \_ discoapi uWSGI worker 13
www-data 18470 10.7  1.0 1366820 166196 ?      Sl   11:32  18:27  \_ discoapi uWSGI worker 14
www-data 18471  6.1  0.7 1352332 118284 ?      Sl   11:32  10:35  \_ discoapi uWSGI worker 15
www-data 18472 13.0  1.1 1377372 193488 ?      Sl   11:32  22:24  \_ discoapi uWSGI worker 16
www-data 18473 23.0  1.2 1426424 203320 ?      Rl   11:32  39:43  \_ discoapi uWSGI worker 17
www-data 18474  1.2  0.8 1356712 138260 ?      Sl   11:32   2:07  \_ discoapi uWSGI worker 18
www-data 18475  9.1  0.7 1327632 131028 ?      Sl   11:32  15:45  \_ discoapi uWSGI worker 19
www-data 18476  2.8  1.0 1380692 168180 ?      Sl   11:32   4:58  \_ discoapi uWSGI worker 20
www-data 18480 46.4  1.3 1344692 227164 ?      R    11:32  80:03  \_ discoapi uWSGI http 1
```

2.0.7
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
www-data 26742  1.4  0.8 1183872 138388 ?      Sl   11:32   2:34 discoapi uWSGI master
www-data 26747  2.4  1.0 1334700 170144 ?      Sl   11:32   4:14  \_ discoapi uWSGI worker 1
www-data 26748 13.7  1.1 1366996 183640 ?      Sl   11:32  23:41  \_ discoapi uWSGI worker 2
www-data 26749  0.7  0.4 1302760 78536 ?       Sl   11:32   1:20  \_ discoapi uWSGI worker 3
www-data 26750 19.8  0.9 1331508 157276 ?      Sl   11:32  34:19  \_ discoapi uWSGI worker 4
www-data 26751 29.9  1.1 1374552 191796 ?      Rl   11:32  51:45  \_ discoapi uWSGI worker 5
www-data 26752  4.5  0.8 1358408 140116 ?      Sl   11:32   7:53  \_ discoapi uWSGI worker 6
www-data 26753  1.3  0.5 1289956 86668 ?       Sl   11:32   2:18  \_ discoapi uWSGI worker 7
www-data 26754 33.7  1.2 1422532 200436 ?      Sl   11:32  58:23  \_ discoapi uWSGI worker 8
www-data 26755  0.6  0.6 1323588 98712 ?       Sl   11:32   1:09  \_ discoapi uWSGI worker 9
www-data 26756 13.8  0.8 1375568 141256 ?      Rl   11:32  24:01  \_ discoapi uWSGI worker 10
www-data 26757 36.6  1.1 1379540 184716 ?      Sl   11:32  63:27  \_ discoapi uWSGI worker 11
www-data 26758  1.0  0.8 1369572 144636 ?      Sl   11:32   1:52  \_ discoapi uWSGI worker 12
www-data 26759  7.3  0.8 1347756 136740 ?      Sl   11:32  12:38  \_ discoapi uWSGI worker 13
www-data 26760  9.2  0.9 1328380 161780 ?      Sl   11:32  15:59  \_ discoapi uWSGI worker 14
www-data 26761 29.3  1.2 1383596 201612 ?      Sl   11:32  50:47  \_ discoapi uWSGI worker 15
www-data 26762  3.3  0.8 1368400 147340 ?      Sl   11:32   5:49  \_ discoapi uWSGI worker 16
www-data 26763  1.8  0.5 1307576 91848 ?       Sl   11:32   3:10  \_ discoapi uWSGI worker 17
www-data 26765  6.0  1.0 1354484 176860 ?      Sl   11:32  10:27  \_ discoapi uWSGI worker 18
www-data 26766  4.9  0.9 1317292 150360 ?      Sl   11:32   8:37  \_ discoapi uWSGI worker 19
www-data 26767 22.1  1.0 1406432 180124 ?      Rl   11:32  38:14  \_ discoapi uWSGI worker 20
www-data 26771 41.5  0.3 1154084 57776 ?       R    11:32  71:48  \_ discoapi uWSGI http 1
```

Any idea of what may have changed?

**Comment by unbit** [comment]
The corerouters memory structure has been increased by 255 bytes in this commit 

https://github.com/unbit/uwsgi/commit/acc270ad81c263a12b076a47513f8b3aabd150ed#diff-a7acc98fd388902c7e32d918ff7f060a

This storage is required for storing (for the whole request time) the name of the current domain/key.

Maybe this is the cause ?

**Comment by edevil** [comment]
So this 2.0.10 instance is using 150MB more RAM, divided by 255 bytes, it would have to be serving 600000 concurrent requests in order for that to be the cause, right? :) I don't think even with memory fragmentation that this alone could explain the increase.

These are the numbers as of now:

2.0.10
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
www-data 18452  1.0  0.8 1183828 138440 ?      Sl   Jul14  14:00 discoapi uWSGI master
www-data 18457  1.4  0.7 1319520 120476 ?      Sl   Jul14  19:34  \_ discoapi uWSGI worker 1
www-data 18458 14.1  1.1 1416768 188636 ?      Sl   Jul14 192:16  \_ discoapi uWSGI worker 2
www-data 18459  3.4  0.9 1337488 148500 ?      Sl   Jul14  47:07  \_ discoapi uWSGI worker 3
www-data 18460  6.6  1.1 1378072 189472 ?      Sl   Jul14  91:15  \_ discoapi uWSGI worker 4
www-data 18461  4.8  0.9 1324420 149160 ?      Sl   Jul14  65:32  \_ discoapi uWSGI worker 5
www-data 18462  1.2  0.7 1324008 124412 ?      Sl   Jul14  16:23  \_ discoapi uWSGI worker 6
www-data 18463  2.6  0.8 1354512 146672 ?      Sl   Jul14  35:34  \_ discoapi uWSGI worker 7
www-data 18464 16.1  1.2 1378652 206944 ?      Rl   Jul14 219:28  \_ discoapi uWSGI worker 8
www-data 18465  3.9  1.0 1369672 174764 ?      Sl   Jul14  53:29  \_ discoapi uWSGI worker 9
www-data 18466  9.0  1.0 1346264 170600 ?      Sl   Jul14 122:53  \_ discoapi uWSGI worker 10
www-data 18467  0.9  0.9 1368048 160468 ?      Sl   Jul14  12:37  \_ discoapi uWSGI worker 11
www-data 18468 12.3  1.1 1355028 186376 ?      Rl   Jul14 168:30  \_ discoapi uWSGI worker 12
www-data 18469 23.8  1.2 1421520 202176 ?      Sl   Jul14 325:33  \_ discoapi uWSGI worker 13
www-data 18470  7.2  1.2 1366816 198900 ?      Sl   Jul14  98:07  \_ discoapi uWSGI worker 14
www-data 18471  6.1  0.7 1352332 118584 ?      Sl   Jul14  84:15  \_ discoapi uWSGI worker 15
www-data 18472 11.4  1.1 1377372 190316 ?      Sl   Jul14 156:25  \_ discoapi uWSGI worker 16
www-data 18473 19.6  1.4 1491944 238188 ?      Sl   Jul14 267:11  \_ discoapi uWSGI worker 17
www-data 18474  0.7  0.9 1364904 161240 ?      Sl   Jul14  10:16  \_ discoapi uWSGI worker 18
www-data 18475  7.9  0.8 1327632 146644 ?      Sl   Jul14 107:53  \_ discoapi uWSGI worker 19
www-data 18476  1.9  1.1 1402844 190384 ?      Sl   Jul14  27:09  \_ discoapi uWSGI worker 20
www-data 18480 37.6  1.5 1360576 261272 ?      S    Jul14 513:15  \_ discoapi uWSGI http 1
```

2.0.7
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
www-data 26742  1.1  0.8 1183872 138364 ?      Sl   Jul14  15:29 discoapi uWSGI master
www-data 26747  2.3  1.0 1338936 174404 ?      Sl   Jul14  32:09  \_ discoapi uWSGI worker 1
www-data 26748  9.1  1.1 1375176 186956 ?      Sl   Jul14 125:08  \_ discoapi uWSGI worker 2
www-data 26749  0.9  1.0 1330156 166296 ?      Sl   Jul14  13:17  \_ discoapi uWSGI worker 3
www-data 26750 12.3  1.0 1403920 174760 ?      Sl   Jul14 168:44  \_ discoapi uWSGI worker 4
www-data 26751 18.0  1.1 1374548 191800 ?      Sl   Jul14 246:20  \_ discoapi uWSGI worker 5
www-data 26752  3.9  1.0 1366604 164868 ?      Rl   Jul14  54:11  \_ discoapi uWSGI worker 6
www-data 26753  1.4  0.7 1318412 126924 ?      Sl   Jul14  19:34  \_ discoapi uWSGI worker 7
www-data 26754 23.0  1.3 1484476 225544 ?      Sl   Jul14 315:08  \_ discoapi uWSGI worker 8
www-data 26755  0.7  0.6 1322564 112656 ?      Sl   Jul14   9:47  \_ discoapi uWSGI worker 9
www-data 26756 11.7  1.0 1381620 174972 ?      Sl   Jul14 161:05  \_ discoapi uWSGI worker 10
www-data 26757 25.2  1.2 1382952 201776 ?      Sl   Jul14 345:47  \_ discoapi uWSGI worker 11
www-data 26758  1.4  1.0 1369572 164988 ?      Sl   Jul14  19:29  \_ discoapi uWSGI worker 12
www-data 26759  6.3  1.1 1413284 181764 ?      Sl   Jul14  86:44  \_ discoapi uWSGI worker 13
www-data 26760  8.5  1.0 1333792 166896 ?      Sl   Jul14 117:30  \_ discoapi uWSGI worker 14
www-data 26761 19.5  1.2 1383588 201900 ?      Rl   Jul14 266:56  \_ discoapi uWSGI worker 15
www-data 26762  3.3  0.8 1368396 147580 ?      Sl   Jul14  46:09  \_ discoapi uWSGI worker 16
www-data 26763  2.1  0.8 1323408 132192 ?      Sl   Jul14  28:47  \_ discoapi uWSGI worker 17
www-data 26765  5.1  1.2 1420028 202300 ?      Sl   Jul14  70:32  \_ discoapi uWSGI worker 18
www-data 26766  4.3  0.9 1319924 153224 ?      Sl   Jul14  59:25  \_ discoapi uWSGI worker 19
www-data 26767 14.1  1.1 1408572 182176 ?      Sl   Jul14 193:27  \_ discoapi uWSGI worker 20
www-data 26771 32.8  0.4 1154528 69948 ?       S    Jul14 448:39  \_ discoapi uWSGI http 1
```

As a side note, I have other 2.0.10 nodes running for 2 months, and this is their state:
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
www-data 14667  1.0  0.6 1183828 105728 ?      Sl   May19 826:22 discoapi uWSGI master
www-data 14701 31.6  2.4 1572552 409872 ?      S    May19 25987:04  \_ discoapi uWSGI http 1
www-data 11663  0.8  1.0 1347576 167284 ?      Sl   Jun30 179:42  \_ discoapi uWSGI worker 1
www-data 11700  0.9  0.9 1346440 152536 ?      Sl   Jun30 201:33  \_ discoapi uWSGI worker 2
www-data 11733  1.2  1.0 1340924 168856 ?      Sl   Jun30 270:58  \_ discoapi uWSGI worker 3
www-data 11849  1.6  1.2 1425684 206204 ?      Sl   Jun30 346:42  \_ discoapi uWSGI worker 4
www-data 12897  1.8  1.2 1391952 199108 ?      Sl   Jun30 403:48  \_ discoapi uWSGI worker 5
www-data 14094  2.5  1.2 1429420 202688 ?      Sl   Jun30 548:06  \_ discoapi uWSGI worker 6
www-data 14127  3.1  1.0 1372920 174672 ?      Sl   Jun30 677:53  \_ discoapi uWSGI worker 7
www-data 14160  3.8  1.0 1397072 168648 ?      Sl   Jun30 835:00  \_ discoapi uWSGI worker 8
www-data 14318  4.9  0.9 1346996 159908 ?      Sl   Jun30 1057:08  \_ discoapi uWSGI worker 9
www-data 15101  5.6  1.0 1357944 177456 ?      Sl   Jun30 1219:17  \_ discoapi uWSGI worker 10
www-data 15129  6.7  1.1 1364168 187932 ?      Sl   Jun30 1451:53  \_ discoapi uWSGI worker 11
www-data 15197  7.6  1.2 1417440 211324 ?      Sl   Jun30 1646:54  \_ discoapi uWSGI worker 12
www-data 15345  8.7  0.9 1340656 160544 ?      Sl   Jun30 1881:19  \_ discoapi uWSGI worker 13
www-data 15378  9.6  1.5 1465144 262664 ?      Rl   Jun30 2080:40  \_ discoapi uWSGI worker 14
www-data 16379 10.9  1.2 1416500 211616 ?      Sl   Jun30 2358:40  \_ discoapi uWSGI worker 15
www-data 16412 12.6  1.9 1567988 317868 ?      Sl   Jun30 2731:32  \_ discoapi uWSGI worker 16
www-data 18773 13.5  1.4 1445716 244196 ?      Sl   Jun30 2908:51  \_ discoapi uWSGI worker 17
www-data 18845 15.4  1.4 1475928 241428 ?      Sl   Jun30 3336:51  \_ discoapi uWSGI worker 18
www-data 19752 18.4  1.2 1496308 210724 ?      Sl   Jun30 3967:43  \_ discoapi uWSGI worker 19
www-data 21990 22.5  1.7 1588388 294596 ?      Rl   Jun30 4866:13  \_ discoapi uWSGI worker 20
```

400MB in 2 months is what makes me think that there is a leak involved, since this instance is serving the same amount of concurrent requests as the previous 2.

**Comment by unbit** [comment]
there are only few patches in the https router. Can you try with 2.0.8 to understand if the problem happened there ? Thanks

**Comment by edevil** [comment]
I tried 2.0.8 when it came out, but I encountered strange problems with it. Compared with 2.0.7 I had lots of broken upload requests so I decided to stay away. A few months ago I needed to upgrade to drop SSL3 and tested 2.0.10 and didn't find upload problems.

**Comment by unbit** [comment]
Ok, i'll make some test, unfortunately openssl seems a cursed library :)

I'll be back as soon as possible

**Comment by unbit** [comment]
This should be fixed in 2.0.11.1. Take in account the memory usage should be lower than 2.0.7 too.

Let me know

**Comment by edevil** [comment]
Great, thanks. I'll leave it running for some time for more meaningful numbers.

**Comment by edevil** [comment]
I can confirm that the memory usage has improved considerably. Also, one of my 2.0.10 nodes that had been running for 2 months just ran out of FDs, I hope this patch solves this as well.

Thanks.

**Comment by jualvarez** [comment]
While investigating a memory issue with the http router, I found this page first, but the actual issue I ran into was https://github.com/unbit/uwsgi/issues/2299 which still happens in some new distributions such as Fedora 39 at the time of writing. I leave the comment for visibility if someone else is running into this.
